<?php
/**
 * export.php — Dump the current prayer_corner database into db/seed.sql
 *
 *   C:\wamp64\bin\php\php8.4.15\php.exe db/export.php
 *
 * This lets you keep seed.sql in sync with whatever changes you make
 * through the app. Run it whenever you want the snapshot updated.
 */

define('DB_HOST', '127.0.0.1');
define('DB_PORT', 3306);
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'prayer_corner');

$target = __DIR__ . '/seed.sql';

try {
    $pdo = new PDO(
        'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=utf8mb4',
        DB_USER,
        DB_PASS,
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
} catch (PDOException $e) {
    fwrite(STDERR, 'ERROR: Could not connect to database: ' . $e->getMessage() . "\n");
    exit(1);
}

function q($v)
{
    return $v === null ? 'NULL' : "'" . str_replace("'", "''", $v) . "'";
}

function table_rows(PDO $pdo, $table)
{
    $stmt = $pdo->query("SELECT * FROM `{$table}`");
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
    if (!$rows) {
        return '';
    }
    $cols = array_map(fn($c) => '`' . $c . '`', array_keys($rows[0]));
    $values = [];
    foreach ($rows as $row) {
        $parts = array_map('q', array_values($row));
        $values[] = '(' . implode(', ', $parts) . ')';
    }
    $lines = [];
    $chunk = 100;
    foreach (array_chunk($values, $chunk) as $group) {
        $lines[] = "\nINSERT INTO `{$table}` (" . implode(', ', $cols) . ') VALUES';
        $lines[] = implode(",\n", $group) . ';';
    }
    return implode("\n", $lines);
}

function next_auto_increment(PDO $pdo, $table)
{
    $stmt = $pdo->query('SHOW TABLE STATUS LIKE ' . $pdo->quote($table));
    return $stmt->fetch()['Auto_increment'];
}

function table_count(PDO $pdo, $table)
{
    return (int) $pdo->query("SELECT COUNT(*) FROM `{$table}`")->fetchColumn();
}

function create_statement(PDO $pdo, $table)
{
    $stmt = $pdo->query('SHOW CREATE TABLE `' . $table . '`');
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    $inner = str_replace('CREATE TABLE `' . $table . '` ', '', $row['Create Table']);
    $inner = preg_replace('/AUTO_INCREMENT=\d+ /', '', $inner);
    return 'CREATE TABLE `' . $table . '` ' . $inner;
}

$tables = ['users', 'prayer_requests', 'prayer_requests_prayed', 'testimonies', 'devotionals', 'fellowship_events'];

$out = [];
$out[] = '-- ============================================================';
$out[] = '-- Prayer Corner — Full Database Seed';
$out[] = '-- Regenerated by db/export.php on ' . date('Y-m-d H:i:s');
$out[] = '-- Run this on a fresh WAMP MySQL (root@127.0.0.1:3306, no password)';
$out[] = '-- Seeded users (except user 1) log in with: Password123!';
$out[] = '-- ============================================================';
$out[] = '';
$out[] = 'DROP DATABASE IF EXISTS `' . DB_NAME . '`;';
$out[] = 'CREATE DATABASE `' . DB_NAME . '`';
$out[] = '  CHARACTER SET utf8mb4';
$out[] = '  COLLATE utf8mb4_unicode_ci;';
$out[] = 'USE `' . DB_NAME . '`;';
$out[] = '';

$out[] = '-- ── Table definitions ─────────────────────────────────────';
$out[] = '';
$out[] = 'SET foreign_key_checks = 0;';
$out[] = '';
foreach ($tables as $table) {
    $out[] = 'DROP TABLE IF EXISTS `' . $table . '`;';
}
$out[] = '';
foreach ($tables as $table) {
    $out[] = create_statement($pdo, $table) . ";";
    $out[] = '';
}
$out[] = 'SET foreign_key_checks = 1;';
$out[] = '';

foreach ($tables as $table) {
    $count = table_count($pdo, $table);
    if ($count === 0) {
        $out[] = '-- ── ' . $table . ' (empty) ───────────────────────────────';
        $out[] = '';
        continue;
    }
    $out[] = '-- ── ' . $table . ' (' . $count . ' rows) ───────────────────';
    $out[] = '';
    $sql = table_rows($pdo, $table);
    $out[] = $sql;
    $out[] = '';
}

$out[] = '-- ── Reset AUTO_INCREMENT counters ─────────────────────────';
$out[] = '';
foreach ($tables as $table) {
    $next = next_auto_increment($pdo, $table);
    if ($next) {
        $out[] = 'ALTER TABLE `' . $table . '` AUTO_INCREMENT = ' . $next . ';';
    }
}
$out[] = '';

$sql = implode("\n", $out);

if (file_put_contents($target, $sql) === false) {
    fwrite(STDERR, "ERROR: Could not write to {$target}\n");
    exit(1);
}

foreach ($tables as $table) {
    printf("%-22s %d rows\n", $table, table_count($pdo, $table));
}
echo "\nWritten to: {$target}\n";