-- ============================================================
-- Prayer Corner — Full Database Seed
-- Regenerated by db/export.php on 2026-09-17 10:46:08
-- Run this on a fresh WAMP MySQL (root@127.0.0.1:3306, no password)
-- Seeded users (except user 1) log in with: Password123!
-- ============================================================

DROP DATABASE IF EXISTS `prayer_corner`;
CREATE DATABASE `prayer_corner`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE `prayer_corner`;

-- ── Table definitions ─────────────────────────────────────

SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `prayer_requests`;
DROP TABLE IF EXISTS `prayer_requests_prayed`;
DROP TABLE IF EXISTS `testimonies`;
DROP TABLE IF EXISTS `devotionals`;
DROP TABLE IF EXISTS `fellowship_events`;

CREATE TABLE `users` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `prayer_requests` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned NOT NULL,
  `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `answered_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `prayer_requests_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `prayer_requests_prayed` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `prayer_request_id` int unsigned NOT NULL,
  `user_id` int unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `prayer_request_id` (`prayer_request_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `prayer_requests_prayed_ibfk_1` FOREIGN KEY (`prayer_request_id`) REFERENCES `prayer_requests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `prayer_requests_prayed_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `testimonies` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `prayer_request_id` int unsigned NOT NULL,
  `user_id` int unsigned NOT NULL,
  `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `prayer_request_id` (`prayer_request_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `testimonies_ibfk_1` FOREIGN KEY (`prayer_request_id`) REFERENCES `prayer_requests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `testimonies_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `devotionals` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `scripture` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `mins` int unsigned NOT NULL DEFAULT '5',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fellowship_events` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `schedule` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `location` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET foreign_key_checks = 1;

-- ── users (10 rows) ───────────────────


INSERT INTO `users` (`id`, `full_name`, `email`, `username`, `password_hash`, `created_at`) VALUES
('1', 'Philip Ayinbora Asungre', 'asungrephilip@gmail.com', 'lover_of_horses', '$2y$10$4F1lkCjJbPEPgYK.p44pHOdODWLpa5TQwHgkIoCNFbPM0OOCFZgde', '2026-09-15 10:56:12'),
('22', 'Sarah Mensah', 'sarah.mensah@example.com', 'sarah_m', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('23', 'David Boateng', 'david.boateng@example.com', 'david_b', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('24', 'Grace Amoah', 'grace.amoah@example.com', 'grace_a', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('25', 'Emmanuel Kumi', 'emmanuel.kumi@example.com', 'emmanuel_k', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('26', 'Abigail Owusu', 'abigail.owusu@example.com', 'abigail_o', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('27', 'Samuel Adjei', 'samuel.adjei@example.com', 'samuel_a', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('28', 'Esther Darko', 'esther.darko@example.com', 'esther_d', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('29', 'Michael Tetteh', 'michael.tetteh@example.com', 'michael_t', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14'),
('30', 'Ruth Anane', 'ruth.anane@example.com', 'ruth_a', '$2y$12$oVMfI3PQU6Np7IbqqhIay.0Sv8O9eSyL3HQItaXiQGEb8oh.HZR8G', '2026-09-16 10:16:14');

-- ── prayer_requests (50 rows) ───────────────────


INSERT INTO `prayer_requests` (`id`, `user_id`, `body`, `created_at`, `answered_at`) VALUES
('101', '1', 'Please pray for our family as we manage a new season of change. We are trusting God for wisdom and unity.', '2026-09-09 04:01:11', NULL),
('102', '1', 'Pray for my health. I have been battling recurring migraines and I am asking the Lord for complete healing.', '2026-09-12 05:54:12', NULL),
('103', '1', 'I am starting a new chapter in my career. Pray for clarity, favour, and that I honour God in all my work.', '2026-09-04 12:51:31', NULL),
('104', '1', 'Please intercede for me as I grow in faith and prayer life. I long for a deeper walk with Christ.', '2026-08-31 19:29:52', NULL),
('105', '1', 'Pray for my loved ones who have not yet accepted Christ. I believe God is still working in their hearts.', '2026-09-08 19:56:02', '2026-09-16 10:58:48'),
('106', '22', 'Please pray for my final exams next week. I have worked hard but I feel anxious and need God''s peace and clarity.', '2026-09-09 09:13:05', NULL),
('107', '22', 'My father needs a successful kidney transplant. The medical team says he is a good candidate, please stand with us in prayer.', '2026-09-07 19:53:41', '2026-09-15 16:16:15'),
('108', '22', 'Pray for unity in my family during this stressful season. Small disagreements keep turning into big arguments.', '2026-09-09 13:43:45', NULL),
('109', '22', 'I am trusting God for a new job opportunity. I have applied to many places and I am waiting on His timing.', '2026-08-26 15:27:37', NULL),
('110', '22', 'Please intercede for my younger sister who has been battling depression. She needs hope and healing from the Lord.', '2026-09-13 07:08:07', NULL),
('111', '23', 'Please pray for my marriage. We love each other but communication has been strained lately, we need wisdom.', '2026-09-04 23:35:35', NULL),
('112', '23', 'I have an important job interview on Thursday. Pray that I present well and that God opens the right door.', '2026-08-31 06:07:09', NULL),
('113', '23', 'Pray for my startup to find stability. Cash flow is tight and I need breakthrough and favour with investors.', '2026-08-26 18:06:20', NULL),
('114', '23', 'My mother has been feeling unwell for weeks and the doctors are not sure what is wrong. Pray for a clear diagnosis.', '2026-09-08 12:43:37', NULL),
('115', '23', 'I am considering relocating to another city for work. Pray for clear direction about whether this move is God''s will.', '2026-09-08 12:50:04', NULL),
('116', '24', 'Lift up my pregnancy in prayer. The doctors have flagged some concerns and I am trusting God for a safe delivery.', '2026-09-04 03:00:12', '2026-09-08 10:16:15'),
('117', '24', 'Pray for my vegetable farming business. The rains failed this season and I need provision for my family.', '2026-09-02 05:55:22', NULL),
('118', '24', 'My church is planning a retreat and I am coordinating it. Pray that everything comes together smoothly.', '2026-08-30 18:11:16', NULL),
('119', '24', 'Please pray for reconciliation with my estranged brother. It has been three years since we last spoke.', '2026-09-08 20:06:43', NULL),
('120', '24', 'I am applying to graduate school. Pray that I gain admission into the programme I have been dreaming of.', '2026-09-14 00:56:21', NULL),
('121', '25', 'Pray for my final year project. I am behind schedule and under a lot of pressure to finish by the deadline.', '2026-08-28 10:36:26', NULL),
('122', '25', 'My grandmother needs surgery to remove a tumour. Pray for the surgeons and for her strength.', '2026-09-11 15:46:43', NULL),
('123', '25', 'I have been struggling with temptation and wanted to ask the community to hold me up in prayer.', '2026-08-31 08:00:45', NULL),
('124', '25', 'Pray for my siblings and I as we plan our father''s funeral. It is a painful time but we trust God.', '2026-09-15 08:52:11', NULL),
('125', '25', 'I am leading a youth Bible study on Fridays. Pray that the young people''s hearts stay open and hungry for God.', '2026-09-15 15:44:57', '2026-09-15 13:16:15'),
('126', '26', 'Please pray for my visa application. I have been waiting for months and my dream job abroad depends on it.', '2026-09-03 16:44:37', NULL),
('127', '26', 'My twins have been sick on and off for a month. Pray for their full rest, protection and good health.', '2026-09-05 16:57:12', NULL),
('128', '26', 'Pray that I find a godly mentor. I sense God is calling me to grow but I need guidance and accountability.', '2026-09-06 18:41:47', NULL),
('129', '26', 'I had a car accident last week. I am grateful to be alive but my leg injury is slow to heal, please pray.', '2026-08-26 17:07:03', NULL),
('130', '26', 'Pray for the children I teach. Many of them face tough home situations and I want to be a source of stability.', '2026-09-15 08:13:49', NULL),
('131', '27', 'Pray for my scholarship application. My family cannot afford my tuition without it and the decision is due soon.', '2026-09-14 09:09:48', NULL),
('132', '27', 'I recently lost my job. Please pray for peace, provision, and the right opportunity to come my way.', '2026-09-08 14:27:47', NULL),
('133', '27', 'My church is about to launch a community feeding programme. Pray for volunteers and enough funds.', '2026-08-31 18:37:09', NULL),
('134', '27', 'Pray for my relationship with my father. We rarely talk and I want to rebuild that bond with grace.', '2026-08-31 11:50:49', '2026-09-12 10:16:15'),
('135', '27', 'I have been waking up with terrible anxiety at night. Pray that God calms my mind and fills me with trust.', '2026-09-15 01:00:13', NULL),
('136', '28', 'Please pray for my new business venture. I am launching a bakery next month and everything needs to align.', '2026-09-06 10:41:08', NULL),
('137', '28', 'My uncle is on life support after a sudden illness. The family is gathered, please hold us up in prayer.', '2026-09-12 01:37:04', NULL),
('138', '28', 'Pray that I overcome my fear of public speaking. I keep being asked to share at church but I freeze up.', '2026-08-31 15:54:23', NULL),
('139', '28', 'I am discerning whether to pursue full-time ministry. Pray for God to make His calling unmistakable.', '2026-09-07 15:02:12', NULL),
('140', '28', 'Pray for my health. I have been dealing with chronic fatigue and I am asking the Lord for strength daily.', '2026-09-16 08:56:41', NULL),
('141', '29', 'Pray for my project team. We are shipping a major release and tensions are high, we need harmony and focus.', '2026-09-06 07:33:57', NULL),
('142', '29', 'My wife and I are hoping for a child. We have been trying for two years and we are trusting God''s timing.', '2026-09-01 13:10:28', NULL),
('143', '29', 'Pray for my knees, they have been painful making it hard to kneel to pray or play with my son.', '2026-09-02 11:05:06', '2026-09-16 07:16:15'),
('144', '29', 'I am mentoring two young men who recently gave their lives to Christ. Pray for wisdom as I disciple them.', '2026-09-04 03:14:37', NULL),
('145', '29', 'Please pray for my brother who has drifted from the faith. Our family intercedes for his return daily.', '2026-09-01 02:40:50', NULL),
('146', '30', 'Pray for my nursing exams. I am studying while working night shifts and I need supernatural energy.', '2026-09-05 04:58:16', NULL),
('147', '30', 'I lost my twin sister two years ago and grief still overwhelms me some days. Pray for my heart''s healing.', '2026-09-13 14:03:17', NULL),
('148', '30', 'Pray for safe travels as I relocate to a new region for work in two weeks.', '2026-09-15 23:51:00', NULL),
('149', '30', 'My mother''s church needs a new roof after the storm. Pray for provision so the congregation can rebuild.', '2026-08-30 04:03:43', NULL),
('150', '30', 'Please pray that I hear clearly from God about a big decision I must make before the end of the year.', '2026-09-07 21:49:04', '2026-09-07 10:16:15');

-- ── prayer_requests_prayed (258 rows) ───────────────────


INSERT INTO `prayer_requests_prayed` (`id`, `prayer_request_id`, `user_id`, `created_at`) VALUES
('246', '101', '23', '2026-09-02 09:33:25'),
('247', '101', '27', '2026-09-12 09:57:32'),
('248', '101', '26', '2026-09-04 09:55:39'),
('249', '101', '22', '2026-09-07 10:06:01'),
('250', '101', '30', '2026-09-15 09:54:08'),
('251', '102', '25', '2026-09-08 09:52:08'),
('252', '102', '22', '2026-09-01 09:30:33'),
('253', '102', '29', '2026-09-06 10:15:51'),
('254', '103', '23', '2026-09-01 10:07:19'),
('255', '103', '24', '2026-09-15 10:09:30'),
('256', '103', '28', '2026-09-12 09:30:03'),
('257', '103', '27', '2026-09-11 09:37:45'),
('258', '103', '25', '2026-09-02 09:42:37'),
('259', '103', '29', '2026-09-10 10:09:56'),
('260', '104', '1', '2026-09-10 09:43:01'),
('261', '104', '26', '2026-09-14 10:08:27'),
('262', '104', '23', '2026-09-01 09:51:12'),
('263', '104', '28', '2026-09-09 09:54:17'),
('264', '104', '29', '2026-09-16 10:08:34'),
('265', '104', '24', '2026-08-30 09:27:39'),
('266', '104', '25', '2026-09-14 09:47:38'),
('267', '104', '30', '2026-09-05 09:44:23'),
('268', '105', '28', '2026-08-30 10:13:15'),
('269', '105', '24', '2026-09-02 10:14:07'),
('270', '105', '23', '2026-09-04 10:14:44'),
('271', '105', '1', '2026-08-31 10:04:15'),
('272', '105', '27', '2026-09-07 09:39:40'),
('273', '105', '22', '2026-09-02 09:52:38'),
('274', '105', '26', '2026-08-29 09:54:51'),
('275', '105', '30', '2026-09-05 09:32:59'),
('276', '105', '29', '2026-08-28 09:59:46'),
('277', '106', '29', '2026-09-04 10:09:59'),
('278', '106', '25', '2026-09-14 10:11:47'),
('279', '106', '1', '2026-09-05 09:30:51'),
('280', '106', '30', '2026-09-12 09:46:55'),
('281', '106', '24', '2026-09-02 09:54:09'),
('282', '106', '22', '2026-09-09 09:46:01'),
('283', '107', '30', '2026-09-16 09:40:32'),
('284', '107', '28', '2026-09-04 10:06:40'),
('285', '107', '25', '2026-09-12 09:44:43'),
('286', '107', '24', '2026-08-30 09:52:59'),
('287', '107', '1', '2026-09-02 10:01:39'),
('288', '107', '27', '2026-09-13 09:55:07'),
('289', '107', '29', '2026-09-13 09:51:01'),
('290', '107', '23', '2026-08-29 09:44:44'),
('291', '108', '30', '2026-09-01 09:39:41'),
('292', '108', '23', '2026-08-29 09:41:07'),
('293', '108', '27', '2026-09-16 10:03:28'),
('294', '108', '26', '2026-09-14 09:41:52'),
('295', '108', '25', '2026-09-03 09:41:08'),
('296', '108', '29', '2026-09-07 09:32:45'),
('297', '108', '28', '2026-09-08 10:01:28'),
('298', '109', '23', '2026-09-08 10:14:37'),
('299', '109', '1', '2026-08-28 09:29:22'),
('300', '109', '26', '2026-09-10 09:52:27'),
('301', '109', '27', '2026-09-10 09:55:02'),
('302', '109', '30', '2026-09-08 09:37:56'),
('303', '109', '22', '2026-09-13 09:43:40'),
('304', '109', '28', '2026-08-28 10:02:57'),
('305', '109', '24', '2026-09-03 10:03:39'),
('306', '109', '25', '2026-09-14 10:10:16'),
('307', '112', '1', '2026-09-06 09:30:40'),
('308', '112', '24', '2026-08-29 09:44:32'),
('309', '112', '25', '2026-09-15 09:54:57'),
('310', '112', '26', '2026-08-30 09:48:58'),
('311', '113', '1', '2026-08-28 09:40:10'),
('312', '113', '30', '2026-08-29 09:34:12'),
('313', '113', '25', '2026-09-08 09:47:30'),
('314', '113', '23', '2026-09-08 10:03:50'),
('315', '114', '22', '2026-09-09 09:54:28'),
('316', '114', '30', '2026-09-10 09:50:31'),
('317', '115', '22', '2026-09-11 09:34:40'),
('318', '115', '30', '2026-09-09 10:04:27'),
('319', '115', '29', '2026-09-13 10:09:50'),
('320', '115', '25', '2026-09-08 10:14:00'),
('321', '115', '24', '2026-09-01 10:08:53'),
('322', '115', '23', '2026-09-08 09:40:07'),
('323', '115', '27', '2026-09-15 10:09:43'),
('324', '115', '28', '2026-09-06 09:55:59'),
('325', '116', '22', '2026-09-09 09:33:53'),
('326', '116', '26', '2026-09-12 09:54:48'),
('327', '116', '1', '2026-09-11 09:42:15'),
('328', '118', '29', '2026-09-04 10:06:37'),
('329', '118', '1', '2026-09-06 09:53:33'),
('330', '118', '22', '2026-09-02 09:37:32'),
('331', '118', '25', '2026-09-10 09:55:09'),
('332', '118', '23', '2026-09-16 09:50:36'),
('333', '118', '30', '2026-09-05 09:48:05'),
('334', '118', '26', '2026-09-03 09:33:14'),
('335', '118', '27', '2026-09-07 10:01:48'),
('336', '119', '28', '2026-09-10 09:55:11'),
('337', '120', '27', '2026-08-28 09:43:33'),
('338', '120', '28', '2026-09-16 10:09:34'),
('339', '120', '25', '2026-08-30 10:12:29'),
('340', '120', '24', '2026-09-07 10:06:30'),
('341', '120', '22', '2026-08-31 10:12:57'),
('342', '120', '1', '2026-09-13 09:31:59'),
('343', '120', '26', '2026-09-12 09:29:26'),
('344', '120', '29', '2026-08-28 09:49:54'),
('345', '120', '30', '2026-08-30 10:11:42');

INSERT INTO `prayer_requests_prayed` (`id`, `prayer_request_id`, `user_id`, `created_at`) VALUES
('346', '122', '23', '2026-09-12 10:14:39'),
('347', '123', '1', '2026-09-07 09:34:03'),
('348', '123', '27', '2026-09-14 09:34:00'),
('349', '123', '26', '2026-09-15 09:47:39'),
('350', '123', '29', '2026-09-10 10:02:01'),
('351', '123', '28', '2026-09-01 09:58:19'),
('352', '123', '24', '2026-09-10 09:48:14'),
('353', '123', '30', '2026-09-02 10:00:49'),
('354', '124', '29', '2026-09-12 09:32:29'),
('355', '124', '24', '2026-09-07 09:35:12'),
('356', '124', '30', '2026-09-01 10:13:40'),
('357', '124', '1', '2026-09-09 09:42:03'),
('358', '124', '25', '2026-09-03 10:01:36'),
('359', '124', '27', '2026-09-16 10:12:18'),
('360', '124', '28', '2026-09-04 10:10:50'),
('361', '125', '25', '2026-09-02 09:45:45'),
('362', '125', '28', '2026-09-12 09:51:34'),
('363', '125', '30', '2026-09-02 09:48:07'),
('364', '125', '26', '2026-09-14 09:26:15'),
('365', '125', '23', '2026-08-31 10:02:32'),
('366', '125', '1', '2026-09-06 10:05:07'),
('367', '125', '22', '2026-09-13 09:59:25'),
('368', '125', '29', '2026-09-15 10:10:46'),
('369', '125', '24', '2026-09-01 09:36:55'),
('370', '126', '23', '2026-09-03 09:31:24'),
('371', '126', '29', '2026-09-12 09:52:21'),
('372', '126', '30', '2026-09-11 09:43:48'),
('373', '126', '1', '2026-09-07 09:47:42'),
('374', '126', '24', '2026-09-13 10:11:36'),
('375', '126', '26', '2026-09-07 09:39:56'),
('376', '127', '24', '2026-08-31 09:31:07'),
('377', '127', '23', '2026-09-16 10:09:57'),
('378', '128', '27', '2026-08-29 09:52:03'),
('379', '128', '25', '2026-08-30 09:42:41'),
('380', '128', '24', '2026-08-28 10:14:10'),
('381', '128', '1', '2026-08-28 09:56:04'),
('382', '129', '28', '2026-09-11 09:28:39'),
('383', '129', '23', '2026-08-30 09:38:34'),
('384', '130', '28', '2026-09-04 09:28:42'),
('385', '130', '22', '2026-09-14 09:51:46'),
('386', '130', '27', '2026-08-28 10:15:53'),
('387', '130', '24', '2026-08-28 10:06:08'),
('388', '130', '30', '2026-09-09 10:14:31'),
('389', '130', '23', '2026-09-10 09:26:42'),
('390', '131', '22', '2026-08-31 09:32:17'),
('391', '131', '23', '2026-09-13 09:56:21'),
('392', '132', '28', '2026-08-28 09:59:58'),
('393', '132', '24', '2026-09-07 09:42:16'),
('394', '132', '1', '2026-08-31 09:32:12'),
('395', '132', '30', '2026-09-09 10:09:54'),
('396', '132', '23', '2026-09-01 10:08:01'),
('397', '132', '25', '2026-09-08 09:49:42'),
('398', '132', '29', '2026-09-03 09:50:17'),
('399', '132', '27', '2026-09-02 10:13:46'),
('400', '133', '29', '2026-09-15 09:54:33'),
('401', '133', '28', '2026-09-16 09:27:24'),
('402', '133', '25', '2026-09-14 09:47:43'),
('403', '133', '26', '2026-09-03 09:33:44'),
('404', '133', '22', '2026-09-16 09:36:20'),
('405', '133', '1', '2026-09-16 09:35:14'),
('406', '133', '30', '2026-09-05 09:32:26'),
('407', '133', '24', '2026-09-15 10:10:35'),
('408', '133', '27', '2026-09-15 09:28:17'),
('409', '134', '28', '2026-09-03 09:39:54'),
('410', '134', '25', '2026-08-30 10:06:35'),
('411', '134', '26', '2026-09-11 10:05:16'),
('412', '135', '22', '2026-09-04 10:06:45'),
('413', '135', '28', '2026-09-04 09:30:05'),
('414', '135', '23', '2026-09-05 09:32:50'),
('415', '135', '1', '2026-09-14 09:33:11'),
('416', '135', '27', '2026-09-09 09:35:23'),
('417', '136', '26', '2026-09-16 10:14:08'),
('418', '136', '28', '2026-09-15 09:41:12'),
('419', '136', '22', '2026-09-06 09:38:03'),
('420', '136', '29', '2026-09-15 10:00:51'),
('421', '136', '24', '2026-09-16 09:42:57'),
('422', '136', '25', '2026-09-02 10:14:57'),
('423', '136', '30', '2026-09-09 09:59:57'),
('424', '136', '27', '2026-09-04 09:54:44'),
('425', '137', '22', '2026-09-01 09:52:55'),
('426', '137', '26', '2026-08-31 10:07:10'),
('427', '137', '30', '2026-08-28 09:51:40'),
('428', '137', '1', '2026-09-03 09:44:52'),
('429', '137', '29', '2026-09-01 09:59:26'),
('430', '137', '28', '2026-09-04 09:30:06'),
('431', '137', '24', '2026-09-11 09:39:40'),
('432', '138', '28', '2026-08-28 10:05:16'),
('433', '138', '24', '2026-09-15 09:43:08'),
('434', '138', '26', '2026-09-11 09:53:38'),
('435', '138', '25', '2026-09-12 09:36:24'),
('436', '138', '29', '2026-09-13 09:37:08'),
('437', '138', '27', '2026-09-01 09:34:23'),
('438', '138', '1', '2026-09-08 09:48:59'),
('439', '138', '22', '2026-09-14 09:51:21'),
('440', '138', '23', '2026-09-05 09:36:20'),
('441', '139', '23', '2026-09-01 10:07:15'),
('442', '139', '27', '2026-09-11 09:57:45'),
('443', '139', '29', '2026-09-08 09:49:47'),
('444', '140', '28', '2026-09-13 10:13:31'),
('445', '140', '29', '2026-09-06 09:50:58');

INSERT INTO `prayer_requests_prayed` (`id`, `prayer_request_id`, `user_id`, `created_at`) VALUES
('446', '140', '27', '2026-09-06 10:02:53'),
('447', '140', '26', '2026-09-06 09:48:39'),
('448', '140', '23', '2026-09-16 09:49:39'),
('449', '140', '22', '2026-09-14 09:36:23'),
('450', '140', '30', '2026-09-15 10:09:55'),
('451', '140', '25', '2026-09-02 10:04:11'),
('452', '141', '27', '2026-09-06 10:03:15'),
('453', '141', '26', '2026-09-01 09:28:53'),
('454', '141', '30', '2026-08-30 09:47:25'),
('455', '141', '28', '2026-09-15 09:36:26'),
('456', '142', '25', '2026-09-15 10:00:14'),
('457', '142', '1', '2026-09-14 09:53:00'),
('458', '142', '26', '2026-09-13 09:47:03'),
('459', '142', '29', '2026-09-15 09:49:05'),
('460', '142', '23', '2026-09-13 09:51:50'),
('461', '143', '25', '2026-09-04 10:10:43'),
('462', '143', '29', '2026-09-11 09:39:06'),
('463', '143', '27', '2026-09-16 09:46:37'),
('464', '143', '23', '2026-09-06 09:56:31'),
('465', '143', '1', '2026-09-16 10:14:10'),
('466', '143', '22', '2026-09-10 09:32:22'),
('467', '143', '24', '2026-09-13 10:05:54'),
('468', '144', '29', '2026-08-29 10:14:17'),
('469', '144', '22', '2026-09-15 09:37:30'),
('470', '144', '25', '2026-09-13 09:27:18'),
('471', '144', '24', '2026-09-16 09:40:55'),
('472', '144', '27', '2026-09-16 10:05:34'),
('473', '145', '30', '2026-09-11 09:44:37'),
('474', '145', '22', '2026-09-12 10:03:35'),
('475', '145', '26', '2026-08-28 09:43:27'),
('476', '145', '1', '2026-09-13 10:00:20'),
('477', '145', '29', '2026-09-11 10:12:53'),
('478', '145', '24', '2026-08-31 09:50:17'),
('479', '145', '25', '2026-09-09 10:00:01'),
('480', '145', '23', '2026-09-01 09:32:23'),
('481', '145', '28', '2026-09-06 10:13:45'),
('482', '146', '27', '2026-08-30 09:40:16'),
('483', '146', '1', '2026-09-03 09:43:26'),
('484', '147', '24', '2026-09-02 09:57:11'),
('485', '147', '27', '2026-09-11 09:36:05'),
('486', '147', '28', '2026-09-02 09:31:47'),
('487', '148', '28', '2026-09-04 09:29:48'),
('488', '148', '26', '2026-08-29 10:01:55'),
('489', '148', '30', '2026-09-16 09:43:50'),
('490', '149', '26', '2026-09-11 09:45:14'),
('491', '149', '28', '2026-09-16 09:47:48'),
('492', '149', '30', '2026-09-03 09:55:19'),
('493', '149', '22', '2026-09-06 09:38:01'),
('494', '149', '27', '2026-09-04 09:33:25'),
('495', '149', '29', '2026-09-06 09:39:09'),
('496', '149', '24', '2026-09-12 10:00:44'),
('497', '149', '25', '2026-09-02 09:54:14'),
('498', '149', '23', '2026-09-13 09:49:18'),
('499', '150', '28', '2026-08-28 09:31:11'),
('500', '150', '23', '2026-09-07 09:36:40'),
('501', '150', '1', '2026-08-30 09:42:37'),
('502', '150', '26', '2026-08-30 09:36:03'),
('503', '150', '25', '2026-09-06 09:56:52');

-- ── testimonies (7 rows) ───────────────────


INSERT INTO `testimonies` (`id`, `prayer_request_id`, `user_id`, `body`, `created_at`) VALUES
('2', '107', '22', 'God answered beyond what I asked. The doctors confirmed the treatment worked and my father is recovering at home. Praise the Lord!', '2026-09-15 18:12:51'),
('3', '116', '24', 'The Lord came through. I passed the exams with good grades and the whole experience deepened my trust in Him.', '2026-09-08 11:48:40'),
('4', '125', '25', 'God moved in a way I did not expect. The door opened at the perfect time and I now have a new opportunity.', '2026-09-15 15:13:29'),
('5', '134', '27', 'Our prayers were answered! Mama is doing much better and the whole family is overwhelmed with gratitude.', '2026-09-12 11:56:38'),
('6', '143', '29', 'The Lord answered clearly. Peace has returned to our home and what seemed impossible became possible.', '2026-09-16 09:05:32'),
('7', '150', '30', 'God did it again. The breakthrough came just when I was about to give up. Forever grateful for this community''s prayers.', '2026-09-07 10:31:19'),
('9', '105', '1', 'God is a GOOOD GOOD GOD', '2026-09-16 10:59:45');

-- ── devotionals (5 rows) ───────────────────


INSERT INTO `devotionals` (`id`, `title`, `scripture`, `body`, `mins`, `created_at`) VALUES
('1', 'Strength in Silence', 'Psalm 46:10', 'In a world that never stops talking, this devotional invites you to find peace in stillness and to listen for the still, small voice of God.', '5', '2026-09-17 10:41:12'),
('2', 'The Courage to Ask', 'Matthew 7:7', 'We often carry burdens alone when God invites us simply to ask. Learn how humble, persistent prayer changes the posture of the heart.', '7', '2026-09-17 10:41:12'),
('3', 'Walking in Forgiveness', 'Colossians 3:13', 'Forgiveness frees the forgiver as much as the forgiven. Reflect on releasing old hurts and extending the grace you have received.', '6', '2026-09-17 10:41:12'),
('4', 'Gratitude That Transforms', '1 Thessalonians 5:18', 'Giving thanks in every circumstance reshapes how we see our day. Discover the practice of counting blessings as a path to joy.', '4', '2026-09-17 10:41:12'),
('5', 'Trusting God''s Timing', 'Ecclesiastes 3:1', 'Waiting on the Lord can feel endless. This devotional explores how seasons of waiting shape faith and mature our trust in His perfect timing.', '6', '2026-09-17 10:41:12');

-- ── fellowship_events (5 rows) ───────────────────


INSERT INTO `fellowship_events` (`id`, `title`, `schedule`, `location`, `body`, `created_at`) VALUES
('1', 'Wednesday Prayer Night', 'Every Wednesday · 7:00 PM', 'Community Hall, Room 2', 'Come together for an evening of worship, intercession, and encouragement.', '2026-09-17 10:41:17'),
('2', 'Friday Bible Study', 'Fridays · 6:30 PM', 'Main Sanctuary', 'Verse-by-verse study of the Gospel of John. All are welcome, bring a friend.', '2026-09-17 10:41:17'),
('3', 'Community Outreach', 'Saturday, October 3 · 9:00 AM', 'Church Parking Lot', 'Join us as we serve our neighborhood with meals, fellowship, and prayer.', '2026-09-17 10:41:17'),
('4', 'Women''s Breakfast', 'Second Saturday · 8:30 AM', 'Fellowship Hall', 'A morning of good food, testimonies, and encouragement for the women of our community.', '2026-09-17 10:41:17'),
('5', 'Youth Praise Night', 'Friday, October 17 · 6:00 PM', 'Main Sanctuary', 'Worship, games, and the Word for young people. Bring a friend and a joyful heart.', '2026-09-17 10:41:17');

-- ── Reset AUTO_INCREMENT counters ─────────────────────────

ALTER TABLE `users` AUTO_INCREMENT = 31;
ALTER TABLE `prayer_requests` AUTO_INCREMENT = 152;
ALTER TABLE `prayer_requests_prayed` AUTO_INCREMENT = 505;
ALTER TABLE `testimonies` AUTO_INCREMENT = 10;
ALTER TABLE `devotionals` AUTO_INCREMENT = 6;
ALTER TABLE `fellowship_events` AUTO_INCREMENT = 6;
